# This file will be joined with docker-compose.app.yml from dcape
# See https://github.com/dopos/dcape

services:
  # This service will extend code from dcape
  app:
    command: start
    environment:
      - KEYCLOAK_ADMIN=${USER_NAME}
      - KEYCLOAK_ADMIN_PASSWORD=${USER_PASS}
      - KC_HOSTNAME=https://${APP_SITE}
      - KC_HOSTNAME_DEBUG=true # see /realms/master/hostname-debug
      - KC_DB=postgres
      - KC_DB_USERNAME=${PGUSER}
      - KC_DB_PASSWORD=${PGPASSWORD}
      - KC_DB_URL_HOST=${PGHOST}
      - KC_DB_URL_DATABASE=${PGDATABASE}
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=forwarded
      - KEYCLOAK_LOGLEVEL=INFO

